interval = 120
splay = 30
splay_first_run = 0

[chef_license]
acceptance = "accept-no-persist"

[automate]
enable = true
environment = "linux"
server_url = "https://192.168.42.106"
token = "E36jw2AQMvVnyxiSE-qJKnNdtaw="
user = "admin"